FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

EXPOSE 3000

# Update to handle Vite's host binding
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]