# Generated by Django 5.0.1 on 2024-12-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'Regular User'), ('GUEST', 'Guest')], default='USER', max_length=20),
        ),
    ]
